apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-server
  template:
    metadata:
      labels:
        app: oauth2-server
    spec:
      containers:
        - name: oauth2-server
          image: oauth2-server:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PRIVATE_KEY_PATH
              value: "/app/keys/private.pem"
            - name: PUBLIC_KEY_PATH
              value: "/app/keys/public.pem"
          volumeMounts:
            - name: key-volume
              mountPath: "/app/keys"
              readOnly: true
      volumes:
        - name: key-volume
          secret:
            secretName: oauth2-keys
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-server
spec:
  selector:
    app: oauth2-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
